import { Email } from "./types";

export const INITIAL_EMAILS: Email[] = [
  {
    id: "mail-1",
    folder: "inbox",
    fromName: "GitHub Security",
    fromEmail: "noreply@github.com",
    toName: "Alex Mercer",
    toEmail: "alex@agentmail.to",
    subject: "GitHub verification code: 849201",
    preview: "Your one-time security authentication code is 849201. This code expires in 10 minutes...",
    body: `Hello Alex,\n\nWe noticed a sign-in attempt from macOS 15.1 in San Francisco, CA.\n\nYour one-time security verification code is:\n\n849201\n\nIf this was not you, please secure your account immediately.\n\nThanks,\nThe GitHub Team`,
    timestamp: "Just now",
    isRead: false,
    isStarred: true,
    otpCode: "849201",
    tags: [
      { label: "OTP / Security", bgColor: "#FED7AA", textColor: "#9A3412" },
      { label: "Clicky Companion", bgColor: "#DDD6FE", textColor: "#5B21B6" },
    ],
  },
  {
    id: "mail-2",
    folder: "inbox",
    fromName: "Netflix Billing",
    fromEmail: "info@mailer.netflix.com",
    toName: "Alex Mercer",
    toEmail: "alex@agentmail.to",
    subject: "Upcoming change to your monthly membership ($22.99/mo)",
    preview: "Your monthly membership price will be adjusted starting next billing cycle. Here are the details...",
    body: `Hi Alex,\n\nWe hope you're enjoying all that Netflix has to offer. We're updating our subscription pricing so we can bring you even more TV shows and movies.\n\nYour Premium plan price will increase to $22.99/month on your next renewal date (October 14, 2026).\n\nIf you don't wish to continue, you can cancel at any time in your account settings.\n\nSincerely,\nThe Netflix Team`,
    timestamp: "10:24 AM",
    isRead: false,
    isStarred: false,
    actionCard: {
      type: "cancellation",
      service: "Netflix Premium",
      costMonthly: "$22.99",
      recommendedAction: "Dispatch Firecrawl crawler to trigger subscription cancellation flow",
      autoTriggerDays: 3,
    },
    tags: [
      { label: "Subscription", bgColor: "#FBCFE8", textColor: "#9D174D" },
      { label: "Action Pending", bgColor: "#FDE68A", textColor: "#854D0E" },
    ],
  },
  {
    id: "mail-3",
    folder: "inbox",
    fromName: "Incogni Privacy Guard",
    fromEmail: "alerts@incogni.com",
    toName: "Alex Mercer",
    toEmail: "alex@agentmail.to",
    subject: "Data broker 'Acxiom' holds your personal profile",
    preview: "Our automated scan discovered personal records including phone number and home address...",
    body: `Hello Alex,\n\nDuring our routine continuous audit of major US data aggregators, our agents confirmed that data broker Acxiom Corporation possesses a public dossier linked to your email.\n\nDetected records:\n- Primary telephone\n- Estimated net worth bracket\n- Residential address history\n\nOur legal agent can automatically issue a CCPA/GDPR removal request under your authority.`,
    timestamp: "Yesterday",
    isRead: true,
    isStarred: true,
    actionCard: {
      type: "data-removal",
      service: "Acxiom Corporation",
      recommendedAction: "Send signed CCPA/GDPR erasure demand to privacy@acxiom.com",
      autoTriggerDays: 5,
    },
    tags: [
      { label: "Privacy Audit", bgColor: "#BBF7D0", textColor: "#166534" },
    ],
  },
  {
    id: "mail-4",
    folder: "inbox",
    fromName: "Garry Tan",
    fromEmail: "garry@ycombinator.com",
    toName: "Alex Mercer",
    toEmail: "alex@agentmail.to",
    subject: "YC S25 Batch Feedback & Prototype Review",
    preview: "Loved the demo video of the Swift companion sniffing the OTP directly from the cursor! A few thoughts...",
    body: `Hey Alex,\n\nSaw the latest Loom showcasing the Clicky-inspired overlay window snapping the OTP code directly next to the cursor focus box. That UX is incredible—it turns email from a tedious browser tab into an ambient operating system capability.\n\nHow is the Convex background queue handling the Firecrawl extraction latency? Let's chat next Tuesday.\n\nBest,\nGarry`,
    timestamp: "Sep 5",
    isRead: true,
    isStarred: true,
    tags: [
      { label: "Investors", bgColor: "#E9D5FF", textColor: "#6B21A8" },
      { label: "High Priority", bgColor: "#FECDD3", textColor: "#9F1239" },
    ],
  },
  {
    id: "mail-5",
    folder: "inbox",
    fromName: "AgentMail Infrastructure",
    fromEmail: "notifications@agentmail.to",
    toName: "Alex Mercer",
    toEmail: "alex@agentmail.to",
    subject: "Global Webhook Connected: 200 OK across all inboxes",
    preview: "Organization-level webhook svix delivery verified. Inbound latency is currently 38ms...",
    body: `Welcome to AgentMail.\n\nYour organization webhook URL https://modern-mail.convex.site/webhooks/agentmail has passed signature verification with Svix.\n\nSystem Metrics:\n- Inbound delivery latency: 38ms\n- Deliverability Score: 99.8%\n- SPF / DKIM: Validated\n\nAll subsequent inbound and outbound events will synchronize in real-time to your Convex instance.`,
    timestamp: "Sep 3",
    isRead: true,
    isStarred: false,
    tags: [
      { label: "System", bgColor: "#E2E8F0", textColor: "#334155" },
    ],
  },

  // Sent Emails
  {
    id: "mail-sent-1",
    folder: "sent",
    fromName: "Alex Mercer",
    fromEmail: "alex@agentmail.to",
    toName: "Adobe Customer Care",
    toEmail: "cancellations@adobe.com",
    subject: "Subscription Cancellation Notice - Account #881920",
    preview: "Per my statutory cancellation rights under FTC guidelines, please terminate Creative Cloud immediately...",
    body: `To whom it may concern,\n\nPlease accept this formal written notice to cancel my Adobe Creative Cloud All Apps subscription associated with alex@agentmail.to (Subscription ID #881920).\n\nI decline any fee concessions or contract extensions. Please provide written confirmation of cancellation and confirm no further auto-debit charges will occur.\n\nBest regards,\nAlex Mercer`,
    timestamp: "Yesterday",
    isRead: true,
    isStarred: false,
    tags: [
      { label: "Negotiation", bgColor: "#FDE68A", textColor: "#854D0E" },
      { label: "Automated Send", bgColor: "#DDD6FE", textColor: "#5B21B6" },
    ],
  },
  {
    id: "mail-sent-2",
    folder: "sent",
    fromName: "Alex Mercer",
    fromEmail: "alex@agentmail.to",
    toName: "Garry Tan",
    toEmail: "garry@ycombinator.com",
    subject: "Re: YC S25 Batch Feedback & Prototype Review",
    preview: "Thanks Garry! We resolved the Firecrawl extraction latency by moving the parsing into Convex background actions...",
    body: `Hi Garry,\n\nThanks for the encouraging feedback!\n\nRegarding the Firecrawl extraction latency: we decoupled it completely. The Convex HTTP action writes the incoming email instantly (<50ms), fires the OTP to the desktop client in real-time, and schedules background jobs for the cancellation and extraction workflows.\n\nTuesday at 2:00 PM PT works great for me. Sending a calendar invite shortly.\n\nBest,\nAlex`,
    timestamp: "Sep 5",
    isRead: true,
    isStarred: true,
    tags: [
      { label: "Outbound", bgColor: "#E2E8F0", textColor: "#334155" },
    ],
  },
  {
    id: "mail-sent-3",
    folder: "sent",
    fromName: "Alex Mercer",
    fromEmail: "alex@agentmail.to",
    toName: "LexisNexis Privacy Team",
    toEmail: "privacy-inquiry@lexisnexis.com",
    subject: "California Consumer Privacy Act (CCPA) Deletion Request",
    preview: "Pursuant to the California Consumer Privacy Act (Cal. Civ. Code § 1798.105), I request deletion...",
    body: `To the LexisNexis Privacy Compliance Team,\n\nPursuant to the California Consumer Privacy Act (Cal. Civ. Code § 1798.105) and applicable state privacy statutes, I hereby request the immediate deletion of all personal identifiers and dossier materials associated with my profile.\n\nPrimary identifier: alex@agentmail.to\n\nPlease confirm compliance within the statutory 45-day response window.\n\nSincerely,\nAlex Mercer`,
    timestamp: "Aug 30",
    isRead: true,
    isStarred: false,
    tags: [
      { label: "Privacy Demand", bgColor: "#BBF7D0", textColor: "#166534" },
    ],
  },
];
